# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 954)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 579, 431))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_3.addWidget(self.checkBox_6)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_3.addWidget(self.checkBox_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 450, 556, 441))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_4.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_4.addWidget(self.checkBox_10)
        self.checkBox_17 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_4.addWidget(self.checkBox_17)
        self.checkBox_11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_4.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_4.addWidget(self.checkBox_12)
        self.checkBox_32 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.checkBox_32.setObjectName("checkBox_32")
        self.horizontalLayout_4.addWidget(self.checkBox_32)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(540, 10, 511, 47))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_18 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout.addWidget(self.checkBox_19)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(540, 380, 511, 47))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_20 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_7.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_7.addWidget(self.checkBox_21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(540, 190, 511, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_22 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_2.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_2.addWidget(self.checkBox_23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(540, 70, 565, 47))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_27 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_27.setObjectName("checkBox_27")
        self.horizontalLayout_8.addWidget(self.checkBox_27)
        self.checkBox_26 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_8.addWidget(self.checkBox_26)
        self.checkBox_33 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_33.setObjectName("checkBox_33")
        self.horizontalLayout_8.addWidget(self.checkBox_33)
        self.checkBox_24 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_8.addWidget(self.checkBox_24)
        self.checkBox_34 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_34.setObjectName("checkBox_34")
        self.horizontalLayout_8.addWidget(self.checkBox_34)
        self.checkBox_25 = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_8.addWidget(self.checkBox_25)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(540, 260, 565, 47))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_28 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_28.setObjectName("checkBox_28")
        self.horizontalLayout_9.addWidget(self.checkBox_28)
        self.checkBox_35 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_35.setObjectName("checkBox_35")
        self.horizontalLayout_9.addWidget(self.checkBox_35)
        self.checkBox_29 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_29.setObjectName("checkBox_29")
        self.horizontalLayout_9.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_30.setObjectName("checkBox_30")
        self.horizontalLayout_9.addWidget(self.checkBox_30)
        self.checkBox_36 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_9.addWidget(self.checkBox_36)
        self.checkBox_31 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_9.addWidget(self.checkBox_31)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(540, 130, 511, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_7)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_10.addWidget(self.horizontalSlider)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(540, 320, 511, 49))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_9)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_12.addWidget(self.horizontalSlider_2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(539, 439, 511, 361))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Image1"))
        self.checkBox_7.setText(_translate("MainWindow", "Real img1"))
        self.checkBox_6.setText(_translate("MainWindow", "Imag img1"))
        self.checkBox.setText(_translate("MainWindow", "Uni_Mag "))
        self.checkBox_5.setText(_translate("MainWindow", "mag img1"))
        self.checkBox_2.setText(_translate("MainWindow", "Uni_Phase"))
        self.checkBox_8.setText(_translate("MainWindow", "phase img1"))
        self.pushButton_2.setText(_translate("MainWindow", "Image2"))
        self.checkBox_9.setText(_translate("MainWindow", "Real img2"))
        self.checkBox_10.setText(_translate("MainWindow", "Imag img2"))
        self.checkBox_17.setText(_translate("MainWindow", "Uni_Mag "))
        self.checkBox_11.setText(_translate("MainWindow", "mag img2"))
        self.checkBox_12.setText(_translate("MainWindow", "phase img2"))
        self.checkBox_32.setText(_translate("MainWindow", "Uni_Phase"))
        self.label_3.setText(_translate("MainWindow", "Which image will you choose for first component in your new image ?"))
        self.checkBox_18.setText(_translate("MainWindow", "Image 1"))
        self.checkBox_19.setText(_translate("MainWindow", "Image2"))
        self.label_4.setText(_translate("MainWindow", "Which components you have chose ?"))
        self.checkBox_20.setText(_translate("MainWindow", "RealAndImaginary"))
        self.checkBox_21.setText(_translate("MainWindow", "PgaseAndMagnitude"))
        self.label_5.setText(_translate("MainWindow", "Which image will you choose for second component in your new image ?"))
        self.checkBox_22.setText(_translate("MainWindow", "Image 1"))
        self.checkBox_23.setText(_translate("MainWindow", "Image2"))
        self.label_6.setText(_translate("MainWindow", "Which  first component will you choose?"))
        self.checkBox_27.setText(_translate("MainWindow", "Real comp"))
        self.checkBox_26.setText(_translate("MainWindow", "Imag comp"))
        self.checkBox_33.setText(_translate("MainWindow", "Uni_Mag "))
        self.checkBox_24.setText(_translate("MainWindow", "Mag comp"))
        self.checkBox_34.setText(_translate("MainWindow", "Uni_Phase"))
        self.checkBox_25.setText(_translate("MainWindow", "Phase comp"))
        self.label_7.setText(_translate("MainWindow", "Which  second component will you choose?"))
        self.checkBox_28.setText(_translate("MainWindow", "Real comp"))
        self.checkBox_35.setText(_translate("MainWindow", "Uni_Mag "))
        self.checkBox_29.setText(_translate("MainWindow", "Imag comp"))
        self.checkBox_30.setText(_translate("MainWindow", "Mag comp"))
        self.checkBox_36.setText(_translate("MainWindow", "Uni_Phase"))
        self.checkBox_31.setText(_translate("MainWindow", "Phase comp"))
        self.label_8.setText(_translate("MainWindow", "How much would the first component contribute in your new image ?"))
        self.label_10.setText(_translate("MainWindow", "Percentage"))
        self.label_11.setText(_translate("MainWindow", "How much would the second component contribute in your new image ?"))
        self.label_12.setText(_translate("MainWindow", "Percentage"))
